function leg = GetLegends(ft)
switch upper(ft)
    case 'TWO'
        leg = {
            'Pref bd Pref dx (all)',...
            'Pref bd null dx (all)',...
            'Pref bd ZERO dx',...
            'Pref bd ZERO dx (correct response)',...
            'null bd ZERO dx (correct response)',...
            'null bd ZERO dx',...
            'null bd Pref dx(flip)',...
            'Pref bd Pref dx', ...
            'null bd null dx ',...
            'pref bd null dx(flip)',...
            'null bd null dx'};
    case {'DID', 'DIDB'}
        leg = {
            'Preferred Id', ... 
            'Null Id', ...
            'Pref Id Correct', ... 
            'Null Id Correct', ...
            'Pref Id Wrong', ...
            'Null Id Wrong', ...
            'Pref dx', ...
            'Null dx', ...
            'pref near zero/p choice', ...
            'pref near zero/n choice', ...
            'null near zero/p choice', ...
            'null near zero/n choice', ...
            'Nearest zero Pref dx', ...
            'Nearest zero null dx', ...
            'All trials put together',...%15
            'Next to 0 dx P - response p', ...
            'Next to 0 dx P - response n', ...
            'Next to 0 dx N - response p', ...
            'Next to 0 dx N - response n', ...
            'dx=0 (Id=0) Pref choice', ...
            'dx=0 (Id=0) Null choice', ...
            'dx=0 (any Id) Pref choice', ...
            'dx=0 (any Id) Null choice', ...
            };
    case 'BDID'
        leg = {
            'Pref bd Pref Id', ...
            'Pref bd null Id',...
            'Pref bd Pref Id P', ...
            'Pref bd Pref Id and incorrect response', ...
            'null bd Null Id C', ...
            'null bd null Id incorrect response', ...
            'Pref Id', ...
            'null Id',...
            'p bd',...
            'n bd',...
            'min bd',...
            'max bd'};
    case 'DPI'
        leg = {
            'dx=0 , pursuit toward pref motion dir', ...
            'dx=0 , pursuit away pref motion dir', ...
            'dx pref , pursuit toward pref motion dir', ...
            'dx pref , pursuit away pref motion dir', ...
            'dx null , pursuit toward pref motion dir', ...
            'dx null , pursuit away pref motion dir', ...
            'pursuit toward pref motion dir', ...
            'pursuit away from pref motion dir', ...
            'dx pref - pursuit away pref dir', ...
            'dx null - pursuit toward pref dir', ...
            'dx = 0 diff', ...
            'dx pref diff', ...
            'dx null diff', ...
            };
    case 'RID'
        leg = {'Pref Or Pref dx','Pref Or null dx','Null Or Pref dx ','null Or null dx'};
%    case 'DIDB'
%        leg = {'Preferred Id', 'Null Id', 'Pref Id Correct', 'Null Id Correct', 'Pref Id Wrong', 'Null Id Wrong', 'Pref dx', 'Null dx' }; %, 'Pref dx Top', 'Null dx Bottom'};
    otherwise
        leg = {'Preferred Id', 'Null Id', 'Biased twoard pref', 'Biased toward Null'};
end
