function leg = GetLegends(ft)
switch upper(ft)
    case 'TWO'
        leg = {
            'Pref bd Pref dx (all)',...
            'Pref bd null dx (all)',...
            'Pref bd ZERO dx',...
            'Pref bd ZERO dx (correct response)',...
            'null bd ZERO dx (correct response)',...
            'null bd ZERO dx',...
            'null bd Pref dx(flip)',...
            'Pref bd Pref dx', ...
            'null bd null dx ',...
            'pref bd null dx(flip)',...
            'null bd null dx', ...
            'Pref dx', ...
            'Null dx', ...
            };
    case {'DID', 'DIDB'}
        leg = {
            'Preferred Id', ... 
            'Null Id', ...
            'Pref Id Correct', ... 
            'Null Id Correct', ...
            'Pref Id Wrong', ...
            'Null Id Wrong', ...
            'Pref dx', ...
            'Null dx', ...
            'pref near zero/p choice', ...
            'pref near zero/n choice', ...
            'null near zero/p choice', ...
            'null near zero/n choice', ...
            'Nearest zero Pref dx', ...
            'Nearest zero null dx', ...
            'All trials put together',...%15
            'Next to 0 dx P - response p', ...
            'Next to 0 dx P - response n', ...
            'Next to 0 dx N - response p', ...
            'Next to 0 dx N - response n', ...
            'dx=0 (Id=0) Pref choice', ...
            'dx=0 (Id=0) Null choice', ...
            'dx=0 (any Id) Pref choice', ...
            'dx=0 (any Id) Null choice', ...
            '','','','','','','','','','','','',''};
    case 'DTRW'
        leg = {...
            'Pref dx, min rw', ...
            'Pref dx, mid rw', ...
            'Pref dx, max rw', ...
            'Null dx, min rw', ...
            'Null dx, mid rw', ...
            'Null dx, max rw', ...  
            'Choice -> pref', ...
            'Choice -> null', ...
            'Choice -> nothing', ...
            };
    case 'BDID'
        leg = {
            'Pref bd Pref Id', ...
            'Pref bd null Id',...
            'Pref bd Pref Id P', ...
            'Pref bd Pref Id and incorrect response', ...
            'null bd Null Id C', ...
            'null bd null Id incorrect response', ...
            'Pref Id', ...
            'null Id',...
            'p bd',...
            'n bd',...
            'min bd',...
            'max bd'};
    case 'DPI'
        leg = {
            '1dx=0 , pursuit toward pref motion dir', ...    % 1
            '2dx=0 , pursuit away pref motion dir', ...      % 2
            '3dx pref , pursuit toward pref motion dir', ... % 3
            '4dx pref , pursuit away pref motion dir', ...   % 4
            '5dx null , pursuit toward pref motion dir', ... % 5
            '6dx null , pursuit away pref motion dir', ...   % 6
            '7pursuit toward pref motion dir', ...           % 7
            '8pursuit away from pref motion dir', ...        % 8
            '9dx pref - pursuit away pref dir', ...          %9
            '10dx null - pursuit toward pref dir', ...            % 10
            '11dx = 0, Positive Pursuit', ... % 11
            '12dx = 0, Negative Pursiut', ... % 12
            '13dx Pref, Positive Pursuit', ... % 13
            '14dx Pref, Negative Pursuit', ... % 14
            '15dx null, Positive Pursuit', ... % 15
            '16dx null, negative Pursuit', ... % 16
            '17-', ...
            '18-', ...
            '19-', ...
            '20pursuit towards pref', ...   % 20
            '21pursuit away from pref', ... % 21
            '22dx pref, pursuit pref', ...  % 22
            '23dx pref, pursuit null', ...  % 23
            '24dx null, pursuit pref', ...  % 24
            '25dx null, pursuit null', ...  % 25
            '26dx = 0, pursuit pref', ...   % 26
            '27dx = 0, pursuit null', ...   % 27
            '28dx = 0 diff', ... % dynamic + 1
            '29dx pref diff', ... % dynamic + 2
            '30dx null diff', ... % dynamic + 3 
            '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', ...
            '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', ...
            '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', ...
            '61', '62', '63', '64', '65', '66', '67', '68', '69', '70'};
    case 'RID'
        leg = {'Pref Or Pref dx','Pref Or null dx','Null Or Pref dx ','null Or null dx'};
%    case 'DIDB'
%        leg = {'Preferred Id', 'Null Id', 'Pref Id Correct', 'Null Id Correct', 'Pref Id Wrong', 'Null Id Wrong', 'Pref dx', 'Null dx' }; %, 'Pref dx Top', 'Null dx Bottom'};
    otherwise
        leg = {'Preferred Id', 'Null Id', 'Biased twoard pref', 'Biased toward Null'};
end
