    figure(1357), clf, hold on,
%     bar([mean(abs(PIPrefdx(~isnan(PIPrefdx)))), mean(abs(PIZerodx(~isnan(PIZerodx)))), mean(abs(PINulldx(~isnan(PINulldx)))), mean(abs(PI(~isnan(PI))))]);
%     errorbar([mean(abs(PIPrefdx(~isnan(PIPrefdx)))), mean(abs(PIZerodx(~isnan(PIZerodx)))), mean(abs(PINulldx(~isnan(PINulldx)))), mean(abs(PI(~isnan(PI))))], ... 
%              [std(abs(PIPrefdx(~isnan(PIPrefdx))))./sqrt(sum(~isnan(PIPrefdx))), std(abs(PIZerodx(~isnan(PIZerodx))))./sqrt(sum(~isnan(PIZerodx))), std(abs(PINulldx(~isnan(PINulldx))))./sqrt(sum(~isnan(PINulldx))), std(abs(PI(~isnan(PI))))./sqrt(sum(~isnan(PI)))]);
%     
%     [a, b, c] = anova1([abs(PI)', abs(PIPrefdx)', abs(PINulldx)', abs(PIZerodx)']);
    PiP = PIPref .* (TI > 0) - PIPref .* (TI < 0);
    PiN = PINull .* (TI > 0) - PINull .* (TI < 0);
    PiZ = PIZero .* (TI > 0) - PIZero .* (TI < 0);
    PiA = PI     .* (TI > 0) - PI     .* (TI < 0);
    
    bar([mean(abs(PiP(~isnan(PiP)))), ...
         mean(abs(PiZ(~isnan(PiZ)))), ...
         mean(abs(PiN(~isnan(PiN)))), ...
         mean(abs(PiA(~isnan(PI)))), ...
         mean(abs(PiA(abs(TI)<0.1)))]);
    errorbar([mean(abs(PiP(~isnan(PiP)))), ...
              mean(abs(PiZ(~isnan(PiZ)))), ...
              mean(abs(PiN(~isnan(PiN)))), ...
              mean(abs(PiA(~isnan(PI)))), ...
              mean(abs(PiA(abs(TI)<0.1)))], ... 
             [std(abs(PiP(~isnan(PiP))))./sqrt(sum(~isnan(PiP))), ...
              std(abs(PiZ(~isnan(PiZ))))./sqrt(sum(~isnan(PiZ))), ...
              std(abs(PiN(~isnan(PiN))))./sqrt(sum(~isnan(PiN))), ...
              std(abs(PiA(~isnan(PI))))./sqrt(sum(~isnan(PI))), ...
              std(abs(PiA(abs(TI)<0.1)))./sqrt(sum(abs(TI)<0.1))]);
    
    [a, b, c] = anova1([abs(PiP)', abs(PiZ)', abs(PiN)', abs(PiA)']);
    multcompare(c);